#!/usr/bin/env bash
# Run Phase 5A-4 condition-fingerprint reranked Transformer decoder.

set -euo pipefail

export SKETCHSMILES_RUN_NAME="${SKETCHSMILES_RUN_NAME:-phase5a4_reranked_transformer_decoder_seed${SKETCHSMILES_SEED:-7}}"
export SKETCHSMILES_TOKENIZATION="${SKETCHSMILES_TOKENIZATION:-smiles_token}"
export SKETCHSMILES_DECODING="${SKETCHSMILES_DECODING:-beam}"
export SKETCHSMILES_BEAM_SIZE="${SKETCHSMILES_BEAM_SIZE:-16}"
export SKETCHSMILES_LENGTH_PENALTY="${SKETCHSMILES_LENGTH_PENALTY:-0.0}"
export SKETCHSMILES_RERANK_MODE="${SKETCHSMILES_RERANK_MODE:-condition_fingerprint}"
export SKETCHSMILES_MODEL_TYPE="${SKETCHSMILES_MODEL_TYPE:-transformer}"
export SKETCHSMILES_TRANSFORMER_LAYERS="${SKETCHSMILES_TRANSFORMER_LAYERS:-4}"
export SKETCHSMILES_ATTENTION_HEADS="${SKETCHSMILES_ATTENTION_HEADS:-8}"
export SKETCHSMILES_CONDITION_TOKENS="${SKETCHSMILES_CONDITION_TOKENS:-8}"
export SKETCHSMILES_DROPOUT="${SKETCHSMILES_DROPOUT:-0.1}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bash "$SCRIPT_DIR/run_phase5a1_learned_smiles_decoder.sh"
