#!/usr/bin/env bash
# Submit Phase 5A-6 randomized-SMILES augmented Transformer decoder to Slurm.

set -euo pipefail

export SKETCHSMILES_RUN_NAME="${SKETCHSMILES_RUN_NAME:-phase5a6_randomized_smiles_decoder_seed${SKETCHSMILES_SEED:-7}}"
export SKETCHSMILES_TOKENIZATION="${SKETCHSMILES_TOKENIZATION:-smiles_token}"
export SKETCHSMILES_DECODING="${SKETCHSMILES_DECODING:-beam}"
export SKETCHSMILES_BEAM_SIZE="${SKETCHSMILES_BEAM_SIZE:-16}"
export SKETCHSMILES_LENGTH_PENALTY="${SKETCHSMILES_LENGTH_PENALTY:-0.0}"
export SKETCHSMILES_RERANK_MODE="${SKETCHSMILES_RERANK_MODE:-condition_fingerprint}"
export SKETCHSMILES_MODEL_TYPE="${SKETCHSMILES_MODEL_TYPE:-transformer}"
export SKETCHSMILES_TRANSFORMER_LAYERS="${SKETCHSMILES_TRANSFORMER_LAYERS:-4}"
export SKETCHSMILES_ATTENTION_HEADS="${SKETCHSMILES_ATTENTION_HEADS:-8}"
export SKETCHSMILES_CONDITION_TOKENS="${SKETCHSMILES_CONDITION_TOKENS:-8}"
export SKETCHSMILES_DROPOUT="${SKETCHSMILES_DROPOUT:-0.1}"
export SKETCHSMILES_RANDOMIZED_SMILES_PER_MOLECULE="${SKETCHSMILES_RANDOMIZED_SMILES_PER_MOLECULE:-4}"
export SKETCHSMILES_RANDOMIZED_SMILES_MAX_ATTEMPTS="${SKETCHSMILES_RANDOMIZED_SMILES_MAX_ATTEMPTS:-32}"
export SKETCHSMILES_SLURM_JOB_NAME="${SKETCHSMILES_SLURM_JOB_NAME:-sketchsmiles-5a6}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export SKETCHSMILES_RUN_SCRIPT="$SCRIPT_DIR/run_phase5a6_randomized_smiles_decoder.sh"
bash "$SCRIPT_DIR/submit_phase5a1_learned_smiles_decoder.sh"
