#!/usr/bin/env bash
# Submit a wider/richer MuMO agentic revise sweep reusing v1 direct proposals.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_DIR="$(cd "$PROJECT_DIR/.." && pwd)"
cd "$REPO_DIR"

BASE_OUTPUT_DIR="${SUCC_EXTERNAL_AGENTIC_BASE_OUTPUT_DIR:-SketchMol-Understanding-Condition/outputs/direct_smiles_external_mumo_agentic_revise_v1}"
export SUCC_EXTERNAL_AGENTIC_DIRECT_PREDICTION_CSV="${SUCC_EXTERNAL_AGENTIC_DIRECT_PREDICTION_CSV:-$BASE_OUTPUT_DIR/direct_smiles_proposals.csv}"
export SUCC_EXTERNAL_AGENTIC_ROWS_CSV="${SUCC_EXTERNAL_AGENTIC_ROWS_CSV:-$BASE_OUTPUT_DIR/external_multiproperty_rows.csv}"
export SUCC_EXTERNAL_AGENTIC_TASK_SPEC_JSON="${SUCC_EXTERNAL_AGENTIC_TASK_SPEC_JSON:-$BASE_OUTPUT_DIR/external_multiproperty_task_specs.json}"

if [[ ! -f "$SUCC_EXTERNAL_AGENTIC_DIRECT_PREDICTION_CSV" ]]; then
  echo "ERROR: missing direct proposal CSV: $SUCC_EXTERNAL_AGENTIC_DIRECT_PREDICTION_CSV" >&2
  echo "Run submit_direct_smiles_external_mumo_agentic_revise.sh first, or set SUCC_EXTERNAL_AGENTIC_DIRECT_PREDICTION_CSV." >&2
  exit 2
fi

export SUCC_EXTERNAL_AGENTIC_OUTPUT_DIR="${SUCC_EXTERNAL_AGENTIC_OUTPUT_DIR:-SketchMol-Understanding-Condition/outputs/direct_smiles_external_mumo_agentic_revise_rich_v1}"
export SUCC_EXTERNAL_AGENTIC_SLURM_JOB_NAME="${SUCC_EXTERNAL_AGENTIC_SLURM_JOB_NAME:-succ-external-mumo-agentic-rich}"
export SUCC_EXTERNAL_AGENTIC_RUN_DIRECT="${SUCC_EXTERNAL_AGENTIC_RUN_DIRECT:-0}"
export SUCC_EXTERNAL_AGENTIC_RUN_FEATURE_EXPORT="${SUCC_EXTERNAL_AGENTIC_RUN_FEATURE_EXPORT:-0}"
export SUCC_EXTERNAL_AGENTIC_GPU_PROFILE="${SUCC_EXTERNAL_AGENTIC_GPU_PROFILE:-none}"
export SUCC_EXTERNAL_AGENTIC_SLURM_TIME="${SUCC_EXTERNAL_AGENTIC_SLURM_TIME:-18:00:00}"
export SUCC_EXTERNAL_AGENTIC_STEPS="${SUCC_EXTERNAL_AGENTIC_STEPS:-2}"
export SUCC_EXTERNAL_AGENTIC_BEAM_SIZE="${SUCC_EXTERNAL_AGENTIC_BEAM_SIZE:-128}"
export SUCC_EXTERNAL_AGENTIC_MAX_CANDIDATES_PER_ROW="${SUCC_EXTERNAL_AGENTIC_MAX_CANDIDATES_PER_ROW:-2048}"
export SUCC_EXTERNAL_AGENTIC_MAX_CANDIDATES_PER_PARENT="${SUCC_EXTERNAL_AGENTIC_MAX_CANDIDATES_PER_PARENT:-256}"
export SUCC_EXTERNAL_AGENTIC_EDIT_ACTION_PROFILE="${SUCC_EXTERNAL_AGENTIC_EDIT_ACTION_PROFILE:-rich}"
export SUCC_EXTERNAL_AGENTIC_SELECTION_MODE="${SUCC_EXTERNAL_AGENTIC_SELECTION_MODE:-similarity_first}"
export SUCC_EXTERNAL_AGENTIC_SIMILARITY_FIRST_MIN_LOCAL_SUCCESS_FRACTION="${SUCC_EXTERNAL_AGENTIC_SIMILARITY_FIRST_MIN_LOCAL_SUCCESS_FRACTION:-1.0}"
export SUCC_EXTERNAL_AGENTIC_SIMILARITY_WEIGHT="${SUCC_EXTERNAL_AGENTIC_SIMILARITY_WEIGHT:-25}"
export SUCC_EXTERNAL_AGENTIC_SIMILARITY_BONUS="${SUCC_EXTERNAL_AGENTIC_SIMILARITY_BONUS:-60}"
export SUCC_EXTERNAL_AGENTIC_COPY_PENALTY="${SUCC_EXTERNAL_AGENTIC_COPY_PENALTY:-8}"

bash "$PROJECT_DIR/scripts/submit_direct_smiles_external_mumo_agentic_revise.sh"
