#!/usr/bin/env bash
# Submit the MuMO one-shot external multi-property baseline.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_DIR="$(cd "$PROJECT_DIR/.." && pwd)"
cd "$REPO_DIR"

export SUCC_EXTERNAL_MULTIPROP_SOURCE_FILE="${SUCC_EXTERNAL_MULTIPROP_SOURCE_FILE:-/scratch/bdong/datasets/Diffusion-Molecule/external/mumo/test.json}"
export SUCC_EXTERNAL_MULTIPROP_SUITE="${SUCC_EXTERNAL_MULTIPROP_SUITE:-mumo}"
export SUCC_EXTERNAL_MULTIPROP_TASK_SPLIT="${SUCC_EXTERNAL_MULTIPROP_TASK_SPLIT:-all}"
export SUCC_EXTERNAL_MULTIPROP_INPUT_SPLIT="${SUCC_EXTERNAL_MULTIPROP_INPUT_SPLIT:-all}"
export SUCC_EXTERNAL_MULTIPROP_MAX_ROWS_PER_TASK="${SUCC_EXTERNAL_MULTIPROP_MAX_ROWS_PER_TASK:-200}"
export SUCC_EXTERNAL_MULTIPROP_OUTPUT_DIR="${SUCC_EXTERNAL_MULTIPROP_OUTPUT_DIR:-SketchMol-Understanding-Condition/outputs/direct_smiles_external_mumo_one_shot_v1}"
export SUCC_EXTERNAL_MULTIPROP_SLURM_JOB_NAME="${SUCC_EXTERNAL_MULTIPROP_SLURM_JOB_NAME:-succ-external-mumo-one-shot}"
export SUCC_EXTERNAL_MULTIPROP_RUN_TRAIN="${SUCC_EXTERNAL_MULTIPROP_RUN_TRAIN:-0}"
export SUCC_EXTERNAL_MULTIPROP_RUN_FEATURE_EXPORT="${SUCC_EXTERNAL_MULTIPROP_RUN_FEATURE_EXPORT:-auto}"
export SUCC_EXTERNAL_MULTIPROP_DISABLE_PROPERTY_RERANK="${SUCC_EXTERNAL_MULTIPROP_DISABLE_PROPERTY_RERANK:-1}"
export SUCC_EXTERNAL_MULTIPROP_NUM_SAMPLES="${SUCC_EXTERNAL_MULTIPROP_NUM_SAMPLES:-20}"

bash "$PROJECT_DIR/scripts/submit_direct_smiles_external_multiproperty_benchmark.sh"
