#!/usr/bin/env bash
# Submit MuMO source-edit group-RL initialized from the source-edit SFT checkpoint.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_DIR="$(cd "$PROJECT_DIR/.." && pwd)"
cd "$REPO_DIR"

SFT_OUTPUT_DIR="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_OUTPUT_DIR:-SketchMol-Understanding-Condition/outputs/direct_smiles_external_mumo_source_edit_sft_v1}"
SFT_CHECKPOINT="${SUCC_EXTERNAL_SOURCE_EDIT_GROUP_RL_RESUME_CHECKPOINT:-$SFT_OUTPUT_DIR/direct_smiles_model_source_edit_sft/direct_smiles_generator.pt}"

export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_TRAIN_SOURCE_FILE="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_TRAIN_SOURCE_FILE:-/scratch/bdong/datasets/Diffusion-Molecule/external/mumo/train.json}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_EVAL_SOURCE_FILE="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_EVAL_SOURCE_FILE:-/scratch/bdong/datasets/Diffusion-Molecule/external/mumo/test.json}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_SUITE="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_SUITE:-mumo}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_TASK_SPLIT="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_TASK_SPLIT:-all}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_MAX_ROWS_PER_TASK="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_MAX_ROWS_PER_TASK:-200}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_OUTPUT_DIR="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_OUTPUT_DIR:-SketchMol-Understanding-Condition/outputs/direct_smiles_external_mumo_source_edit_sft_group_rl_v1}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_RESUME_CHECKPOINT="$SFT_CHECKPOINT"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_CONDITION_MIXING_MODE="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_CONDITION_MIXING_MODE:-append_source_property_program}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_DISABLE_PROPERTY_RERANK="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_DISABLE_PROPERTY_RERANK:-1}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_SLURM_JOB_NAME="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_SLURM_JOB_NAME:-succ-external-mumo-source-edit-rl}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_SFT_WEIGHT="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_SFT_WEIGHT:-0.5}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_REWARD_SOURCE_SIMILARITY_WEIGHT="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_REWARD_SOURCE_SIMILARITY_WEIGHT:-2.0}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_REWARD_STRICT_WEIGHT="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_REWARD_STRICT_WEIGHT:-1.5}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_REWARD_DISTANCE_WEIGHT="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_REWARD_DISTANCE_WEIGHT:-0.05}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_BENCHMARK_NUM_SAMPLES="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_BENCHMARK_NUM_SAMPLES:-20}"

if [[ ! -f "$SFT_CHECKPOINT" ]]; then
  echo "ERROR: source-edit SFT checkpoint not found: $SFT_CHECKPOINT" >&2
  echo "Run submit_direct_smiles_external_mumo_source_edit_sft.sh first, or set SUCC_EXTERNAL_SOURCE_EDIT_GROUP_RL_RESUME_CHECKPOINT." >&2
  exit 2
fi

bash "$PROJECT_DIR/scripts/submit_direct_smiles_external_multiproperty_group_rl.sh"
