#!/usr/bin/env bash
# Submit a longer source-edit SFT run to test whether the direct model simply underfit MuMO source conditioning.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_DIR="$(cd "$PROJECT_DIR/.." && pwd)"
cd "$REPO_DIR"

export SUCC_EXTERNAL_SOURCE_EDIT_SFT_OUTPUT_DIR="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_OUTPUT_DIR:-SketchMol-Understanding-Condition/outputs/direct_smiles_external_mumo_source_edit_sft_long_v1}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_SLURM_JOB_NAME="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_SLURM_JOB_NAME:-succ-external-mumo-source-edit-sft-long}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_EPOCHS="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_EPOCHS:-5}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_LR="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_LR:-7e-6}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_BATCH_SIZE="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_BATCH_SIZE:-24}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_EVAL_BATCH_SIZE="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_EVAL_BATCH_SIZE:-24}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_MAX_ROWS_PER_TASK="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_MAX_ROWS_PER_TASK:-400}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_NUM_SAMPLES="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_NUM_SAMPLES:-64}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_PARALLEL_SAMPLES="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_PARALLEL_SAMPLES:-8}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_MAX_PARALLEL_SEQUENCES="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_MAX_PARALLEL_SEQUENCES:-1024}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_TEMPERATURE="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_TEMPERATURE:-0.55}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_TOP_K="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_TOP_K:-20}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_TOP_P="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_TOP_P:-0.9}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_RESET_TRAINING_STATE="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_RESET_TRAINING_STATE:-1}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_DISABLE_PROPERTY_RERANK="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_DISABLE_PROPERTY_RERANK:-1}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_SLURM_TIME="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_SLURM_TIME:-30:00:00}"
export SUCC_EXTERNAL_SOURCE_EDIT_SFT_SLURM_MEM="${SUCC_EXTERNAL_SOURCE_EDIT_SFT_SLURM_MEM:-128G}"

bash "$PROJECT_DIR/scripts/submit_direct_smiles_external_mumo_source_edit_sft.sh"
