#!/usr/bin/env bash
# Re-evaluate the existing source-edit group-RL checkpoint with candidate-level official aggregation.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_DIR="$(cd "$PROJECT_DIR/.." && pwd)"
cd "$REPO_DIR"

RL_CHECKPOINT="${SUCC_EXTERNAL_SOURCE_EDIT_RL_OFFICIAL_CHECKPOINT:-SketchMol-Understanding-Condition/outputs/direct_smiles_external_mumo_source_edit_sft_group_rl_v1/direct_smiles_model_group_rl/direct_smiles_generator_rl.pt}"

if [[ ! -f "$RL_CHECKPOINT" ]]; then
  echo "ERROR: source-edit RL checkpoint not found: $RL_CHECKPOINT" >&2
  echo "Set SUCC_EXTERNAL_SOURCE_EDIT_RL_OFFICIAL_CHECKPOINT or run submit_direct_smiles_external_mumo_source_edit_sft_group_rl.sh first." >&2
  exit 2
fi

export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_OUTPUT_DIR="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_OUTPUT_DIR:-SketchMol-Understanding-Condition/outputs/direct_smiles_external_mumo_source_edit_rl_official_rerun_v1}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_TRAIN_SOURCE_FILE="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_TRAIN_SOURCE_FILE:-/scratch/bdong/datasets/Diffusion-Molecule/external/mumo/train.json}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_EVAL_SOURCE_FILE="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_EVAL_SOURCE_FILE:-/scratch/bdong/datasets/Diffusion-Molecule/external/mumo/test.json}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_SUITE="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_SUITE:-mumo}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_TASK_SPLIT="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_TASK_SPLIT:-all}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_MAX_ROWS_PER_TASK="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_MAX_ROWS_PER_TASK:-200}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_MODEL_DIR="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_MODEL_DIR:-$SUCC_EXTERNAL_MULTIPROP_GROUP_RL_OUTPUT_DIR/direct_smiles_model_group_rl}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_RL_CHECKPOINT="$RL_CHECKPOINT"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_RUN_TRAIN=0
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_RUN_BENCHMARK_AFTER_TRAIN=1
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_SLURM_JOB_NAME="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_SLURM_JOB_NAME:-succ-external-mumo-source-edit-rl-official}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_CONDITION_MIXING_MODE="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_CONDITION_MIXING_MODE:-append_source_property_program}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_DISABLE_PROPERTY_RERANK="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_DISABLE_PROPERTY_RERANK:-1}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_BENCHMARK_NUM_SAMPLES="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_BENCHMARK_NUM_SAMPLES:-64}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_BENCHMARK_PARALLEL_SAMPLES="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_BENCHMARK_PARALLEL_SAMPLES:-8}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_BENCHMARK_MAX_PARALLEL_SEQUENCES="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_BENCHMARK_MAX_PARALLEL_SEQUENCES:-1024}"
export SUCC_EXTERNAL_MULTIPROP_GROUP_RL_SLURM_TIME="${SUCC_EXTERNAL_MULTIPROP_GROUP_RL_SLURM_TIME:-12:00:00}"

bash "$PROJECT_DIR/scripts/submit_direct_smiles_external_multiproperty_group_rl.sh"
