#!/usr/bin/env bash
# Submit dual-mode SUCC training: MolEdit Table1 edits + de novo 2p-7p + OOD rows.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export DM_DATA_ROOT="${DM_DATA_ROOT:-/scratch/bdong/datasets/Diffusion-Molecule}"
export SUCC_DATASET_MODE=dualmode
export SUCC_UNIFIED_OUTPUT_DIR="${SUCC_UNIFIED_OUTPUT_DIR:-SketchMol-Understanding-Condition/outputs/univideo_molecule_generation_moledit_instruct_dualmode_v1}"
export SUCC_CONDITION_FEATURES_DIR="${SUCC_CONDITION_FEATURES_DIR:-SketchMol-Understanding-Condition/outputs/condition_features_moledit_hf_vlm_dualmode_v1}"
export SUCC_HF_MODEL_NAME_OR_PATH="${SUCC_HF_MODEL_NAME_OR_PATH:-/scratch/bdong/checkpoints/Qwen2.5-VL-7B-Instruct}"
export SUCC_MOLEDIT_TRAIN_SPLIT="${SUCC_MOLEDIT_TRAIN_SPLIT:-$DM_DATA_ROOT/processed/moledit-instruct/enhanced_v1/splits/train.csv}"
export SUCC_MOLEDIT_EVAL_SPLIT="${SUCC_MOLEDIT_EVAL_SPLIT:-$DM_DATA_ROOT/processed/moledit-instruct/enhanced_v1/splits/eval_balanced.csv}"
export SUCC_DENOVO_MOLECULE_DB_CSV="${SUCC_DENOVO_MOLECULE_DB_CSV:-SketchMol-MultiProperty-EditDataset/outputs/multiproperty_source_neighbor_v1/molecule_database.csv}"

# MolEdit Table1 core
export SUCC_MOLEDIT_TABLE1_TASKS_ONLY="${SUCC_MOLEDIT_TABLE1_TASKS_ONLY:-1}"
export SUCC_MOLEDIT_BALANCED_TRAIN_PER_TASK="${SUCC_MOLEDIT_BALANCED_TRAIN_PER_TASK:-12000}"
export SUCC_MOLEDIT_BALANCED_EVAL_PER_TASK="${SUCC_MOLEDIT_BALANCED_EVAL_PER_TASK:-100}"
export SUCC_MOLEDIT_TRAIN_LIMIT="${SUCC_MOLEDIT_TRAIN_LIMIT:-90000}"
export SUCC_MOLEDIT_EVAL_LIMIT="${SUCC_MOLEDIT_EVAL_LIMIT:-1000}"

# Dual-mode de novo / OOD mixing
export SUCC_DENOVO_EVAL_ROWS_PER_PROPERTY_COUNT="${SUCC_DENOVO_EVAL_ROWS_PER_PROPERTY_COUNT:-1000}"
export SUCC_DENOVO_TRAIN_ROWS_PER_PROPERTY_COUNT="${SUCC_DENOVO_TRAIN_ROWS_PER_PROPERTY_COUNT:-500}"
export SUCC_OOD_EVAL_ROWS_PER_SPEC="${SUCC_OOD_EVAL_ROWS_PER_SPEC:-100}"
export SUCC_OOD_TRAIN_ROWS_PER_SPEC="${SUCC_OOD_TRAIN_ROWS_PER_SPEC:-200}"

export SUCC_MIN_EDIT_SOURCE_TANIMOTO="${SUCC_MIN_EDIT_SOURCE_TANIMOTO:-0.0}"
export SUCC_REQUIRE_EDIT_QUALITY_COLUMNS=0
export SUCC_REQUIRE_EVAL_ORACLE_STRICT=0

# Latent / optimization: inherit v3 attack defaults, tuned for broader coverage.
export SUCC_LATENT_BACKEND="${SUCC_LATENT_BACKEND:-image_vae}"
export SUCC_LATENT_TARGET_MODE="${SUCC_LATENT_TARGET_MODE:-residual}"
export SUCC_DIFFUSION_OBJECTIVE="${SUCC_DIFFUSION_OBJECTIVE:-pred_x0}"
export SUCC_RESIDUAL_SAMPLE_SCALE="${SUCC_RESIDUAL_SAMPLE_SCALE:-1.45}"
export SUCC_CONNECTOR_LATENT_BLEND="${SUCC_CONNECTOR_LATENT_BLEND:-0.20}"
export SUCC_SAMPLE_STEPS="${SUCC_SAMPLE_STEPS:-48}"
export SUCC_SAMPLE_ETA="${SUCC_SAMPLE_ETA:-0.0}"
export SUCC_IMAGE_VAE_INK_LOSS_WEIGHT="${SUCC_IMAGE_VAE_INK_LOSS_WEIGHT:-4.0}"

export SUCC_STAGE1_EPOCHS="${SUCC_STAGE1_EPOCHS:-4}"
export SUCC_STAGE2_EPOCHS="${SUCC_STAGE2_EPOCHS:-14}"
export SUCC_STAGE3_EPOCHS="${SUCC_STAGE3_EPOCHS:-6}"
export SUCC_BATCH_SIZE="${SUCC_BATCH_SIZE:-48}"
export SUCC_EVAL_BATCH_SIZE="${SUCC_EVAL_BATCH_SIZE:-64}"
export SUCC_AUX_LOSS_WEIGHT="${SUCC_AUX_LOSS_WEIGHT:-0.90}"
export SUCC_SAMPLING_STRATEGY="${SUCC_SAMPLING_STRATEGY:-weighted}"
export SUCC_TABLE1_SAMPLE_WEIGHT="${SUCC_TABLE1_SAMPLE_WEIGHT:-5.0}"
export SUCC_TRAIN_PROPERTY_SAMPLE_WEIGHTS="${SUCC_TRAIN_PROPERTY_SAMPLE_WEIGHTS:-MW=6,SA=6,RB=4,HBA=4,QED=3,LogP=3}"
export SUCC_AUX_PROPERTY_WEIGHTS="${SUCC_AUX_PROPERTY_WEIGHTS:-MW=5,SA=5,RB=4,HBA=4,QED=3,LogP=3}"
export SUCC_AUX_ALL_PROPERTIES="${SUCC_AUX_ALL_PROPERTIES:-1}"
export SUCC_CONDITION_DROPOUT="${SUCC_CONDITION_DROPOUT:-0.05}"
export SUCC_SOURCE_DROPOUT="${SUCC_SOURCE_DROPOUT:-0.30}"

export SUCC_RUN_DATASET_EXPORT="${SUCC_RUN_DATASET_EXPORT:-1}"
export SUCC_RUN_FEATURE_EXPORT="${SUCC_RUN_FEATURE_EXPORT:-auto}"
export SUCC_DECODE_EVAL_IMAGES=0
export SUCC_RUN_IMAGE_STRUCTURE_BENCHMARK=0
export SUCC_RUN_MOLSCRIBE_OCR=0
export SUCC_SUBMIT_MATERIALIZED_BENCHMARK_AFTER="${SUCC_SUBMIT_MATERIALIZED_BENCHMARK_AFTER:-0}"
export SUCC_SUBMIT_TABLE1_EXTENSION_AFTER="${SUCC_SUBMIT_TABLE1_EXTENSION_AFTER:-0}"
export SUCC_SUBMIT_DENOVO_BENCHMARK_AFTER="${SUCC_SUBMIT_DENOVO_BENCHMARK_AFTER:-0}"
export SUCC_SUBMIT_OOD_BENCHMARK_AFTER="${SUCC_SUBMIT_OOD_BENCHMARK_AFTER:-0}"

if [[ -z "${SUCC_IMAGE_VAE_CHECKPOINT:-}" ]]; then
  CANONICAL_VAE="SketchMol-Understanding-Condition/outputs/univideo_molecule_generation_v2_residual_ink/molecule_image_vae/molecule_image_vae.pt"
  if [[ -f "$CANONICAL_VAE" ]]; then
    export SUCC_IMAGE_VAE_CHECKPOINT="$CANONICAL_VAE"
    export SUCC_IMAGE_VAE_DIR="$(dirname "$CANONICAL_VAE")"
    export SUCC_RUN_IMAGE_VAE_TRAIN="${SUCC_RUN_IMAGE_VAE_TRAIN:-0}"
  fi
fi
export SUCC_RUN_IMAGE_VAE_TRAIN="${SUCC_RUN_IMAGE_VAE_TRAIN:-auto}"

echo "Submitting SUCC UniVideo MolEdit dual-mode pipeline"
echo "  output_dir=$SUCC_UNIFIED_OUTPUT_DIR"
echo "  dataset_mode=$SUCC_DATASET_MODE"
echo "  denovo_train_rows_per_property_count=$SUCC_DENOVO_TRAIN_ROWS_PER_PROPERTY_COUNT"
echo "  ood_train_rows_per_spec=$SUCC_OOD_TRAIN_ROWS_PER_SPEC"
echo "  source_dropout=$SUCC_SOURCE_DROPOUT"
echo "  balanced_train_per_task=$SUCC_MOLEDIT_BALANCED_TRAIN_PER_TASK"

bash "$SCRIPT_DIR/submit_univideo_molecule_pipeline.sh"
