#!/usr/bin/env bash
# Submit a larger rich local-edit revise run.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_DIR="$(cd "$PROJECT_DIR/.." && pwd)"
cd "$REPO_DIR"

export SUCC_EXTERNAL_AGENTIC_OUTPUT_DIR="${SUCC_EXTERNAL_AGENTIC_OUTPUT_DIR:-SketchMol-Understanding-Condition/outputs/direct_smiles_external_mumo_agentic_revise_rich_x2_v1}"
export SUCC_EXTERNAL_AGENTIC_SLURM_JOB_NAME="${SUCC_EXTERNAL_AGENTIC_SLURM_JOB_NAME:-succ-external-mumo-agentic-rich-x2}"
export SUCC_EXTERNAL_AGENTIC_RUN_DIRECT="${SUCC_EXTERNAL_AGENTIC_RUN_DIRECT:-0}"
export SUCC_EXTERNAL_AGENTIC_RUN_FEATURE_EXPORT="${SUCC_EXTERNAL_AGENTIC_RUN_FEATURE_EXPORT:-0}"
export SUCC_EXTERNAL_AGENTIC_GPU_PROFILE="${SUCC_EXTERNAL_AGENTIC_GPU_PROFILE:-none}"
export SUCC_EXTERNAL_AGENTIC_SLURM_TIME="${SUCC_EXTERNAL_AGENTIC_SLURM_TIME:-30:00:00}"
export SUCC_EXTERNAL_AGENTIC_SLURM_MEM="${SUCC_EXTERNAL_AGENTIC_SLURM_MEM:-96G}"
export SUCC_EXTERNAL_AGENTIC_STEPS="${SUCC_EXTERNAL_AGENTIC_STEPS:-2}"
export SUCC_EXTERNAL_AGENTIC_BEAM_SIZE="${SUCC_EXTERNAL_AGENTIC_BEAM_SIZE:-192}"
export SUCC_EXTERNAL_AGENTIC_MAX_CANDIDATES_PER_ROW="${SUCC_EXTERNAL_AGENTIC_MAX_CANDIDATES_PER_ROW:-4096}"
export SUCC_EXTERNAL_AGENTIC_MAX_CANDIDATES_PER_PARENT="${SUCC_EXTERNAL_AGENTIC_MAX_CANDIDATES_PER_PARENT:-384}"
export SUCC_EXTERNAL_AGENTIC_EDIT_ACTION_PROFILE="${SUCC_EXTERNAL_AGENTIC_EDIT_ACTION_PROFILE:-rich}"
export SUCC_EXTERNAL_AGENTIC_SELECTION_MODE="${SUCC_EXTERNAL_AGENTIC_SELECTION_MODE:-similarity_first}"
export SUCC_EXTERNAL_AGENTIC_SIMILARITY_FIRST_MIN_LOCAL_SUCCESS_FRACTION="${SUCC_EXTERNAL_AGENTIC_SIMILARITY_FIRST_MIN_LOCAL_SUCCESS_FRACTION:-0.9}"
export SUCC_EXTERNAL_AGENTIC_PROPERTY_WEIGHT="${SUCC_EXTERNAL_AGENTIC_PROPERTY_WEIGHT:-80}"
export SUCC_EXTERNAL_AGENTIC_DISTANCE_WEIGHT="${SUCC_EXTERNAL_AGENTIC_DISTANCE_WEIGHT:-8}"
export SUCC_EXTERNAL_AGENTIC_SIMILARITY_WEIGHT="${SUCC_EXTERNAL_AGENTIC_SIMILARITY_WEIGHT:-70}"
export SUCC_EXTERNAL_AGENTIC_SIMILARITY_BONUS="${SUCC_EXTERNAL_AGENTIC_SIMILARITY_BONUS:-160}"
export SUCC_EXTERNAL_AGENTIC_COPY_PENALTY="${SUCC_EXTERNAL_AGENTIC_COPY_PENALTY:-10}"

bash "$PROJECT_DIR/scripts/submit_direct_smiles_external_mumo_agentic_revise.sh"
