#!/usr/bin/env bash
# Submit a source-similarity anchored GraphEditDSL policy sweep.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_DIR="$(cd "$PROJECT_DIR/.." && pwd)"
cd "$REPO_DIR"

export SUCC_EXTERNAL_GRAPH_EDIT_OUTPUT_DIR="${SUCC_EXTERNAL_GRAPH_EDIT_OUTPUT_DIR:-SketchMol-Understanding-Condition/outputs/direct_smiles_external_mumo_graph_edit_policy_sim_anchor_v1}"
export SUCC_EXTERNAL_GRAPH_EDIT_SLURM_JOB_NAME="${SUCC_EXTERNAL_GRAPH_EDIT_SLURM_JOB_NAME:-succ-external-mumo-graph-policy-sim}"
export SUCC_EXTERNAL_GRAPH_EDIT_PLANNER_MODE="${SUCC_EXTERNAL_GRAPH_EDIT_PLANNER_MODE:-policy_graph_dsl}"
export SUCC_EXTERNAL_GRAPH_EDIT_SELECTION_MODE="${SUCC_EXTERNAL_GRAPH_EDIT_SELECTION_MODE:-similarity_first}"
export SUCC_EXTERNAL_GRAPH_EDIT_PLANNER_STEPS="${SUCC_EXTERNAL_GRAPH_EDIT_PLANNER_STEPS:-2}"
export SUCC_EXTERNAL_GRAPH_EDIT_BEAM_SIZE="${SUCC_EXTERNAL_GRAPH_EDIT_BEAM_SIZE:-96}"
export SUCC_EXTERNAL_GRAPH_EDIT_SITE_LIMIT="${SUCC_EXTERNAL_GRAPH_EDIT_SITE_LIMIT:-48}"
export SUCC_EXTERNAL_GRAPH_EDIT_MAX_PLANS_PER_PROPERTY="${SUCC_EXTERNAL_GRAPH_EDIT_MAX_PLANS_PER_PROPERTY:-128}"
export SUCC_EXTERNAL_GRAPH_EDIT_MAX_CANDIDATES_PER_PARENT="${SUCC_EXTERNAL_GRAPH_EDIT_MAX_CANDIDATES_PER_PARENT:-128}"
export SUCC_EXTERNAL_GRAPH_EDIT_MAX_CANDIDATES_PER_ROW="${SUCC_EXTERNAL_GRAPH_EDIT_MAX_CANDIDATES_PER_ROW:-2048}"
export SUCC_EXTERNAL_GRAPH_EDIT_SIMILARITY_FIRST_MIN_LOCAL_SUCCESS_FRACTION="${SUCC_EXTERNAL_GRAPH_EDIT_SIMILARITY_FIRST_MIN_LOCAL_SUCCESS_FRACTION:-0.75}"
export SUCC_EXTERNAL_GRAPH_EDIT_PROPERTY_WEIGHT="${SUCC_EXTERNAL_GRAPH_EDIT_PROPERTY_WEIGHT:-45}"
export SUCC_EXTERNAL_GRAPH_EDIT_DISTANCE_WEIGHT="${SUCC_EXTERNAL_GRAPH_EDIT_DISTANCE_WEIGHT:-4}"
export SUCC_EXTERNAL_GRAPH_EDIT_SIMILARITY_WEIGHT="${SUCC_EXTERNAL_GRAPH_EDIT_SIMILARITY_WEIGHT:-120}"
export SUCC_EXTERNAL_GRAPH_EDIT_SIMILARITY_BONUS="${SUCC_EXTERNAL_GRAPH_EDIT_SIMILARITY_BONUS:-260}"
export SUCC_EXTERNAL_GRAPH_EDIT_COPY_PENALTY="${SUCC_EXTERNAL_GRAPH_EDIT_COPY_PENALTY:-14}"
export SUCC_EXTERNAL_GRAPH_EDIT_GPU_PROFILE="${SUCC_EXTERNAL_GRAPH_EDIT_GPU_PROFILE:-none}"
export SUCC_EXTERNAL_GRAPH_EDIT_SLURM_TIME="${SUCC_EXTERNAL_GRAPH_EDIT_SLURM_TIME:-18:00:00}"
export SUCC_EXTERNAL_GRAPH_EDIT_SLURM_MEM="${SUCC_EXTERNAL_GRAPH_EDIT_SLURM_MEM:-96G}"

bash "$PROJECT_DIR/scripts/submit_direct_smiles_external_mumo_graph_edit_agent.sh"
