#!/usr/bin/env bash
# Submit a larger-capacity Phase 5A-4 Transformer run.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SEED="${SKETCHMOL_COMPARE_SEED:-${SKETCHSMILES_SEED:-7}}"

export SKETCHSMILES_SEED="$SEED"
export SKETCHSMILES_RUN_NAME="${SKETCHSMILES_RUN_NAME:-sketchmol_compare_phase5a4_large_seed${SEED}}"
export SKETCHSMILES_HIDDEN_DIM="${SKETCHSMILES_HIDDEN_DIM:-512}"
export SKETCHSMILES_EMBEDDING_DIM="${SKETCHSMILES_EMBEDDING_DIM:-128}"
export SKETCHSMILES_TRANSFORMER_LAYERS="${SKETCHSMILES_TRANSFORMER_LAYERS:-6}"
export SKETCHSMILES_ATTENTION_HEADS="${SKETCHSMILES_ATTENTION_HEADS:-8}"
export SKETCHSMILES_CONDITION_TOKENS="${SKETCHSMILES_CONDITION_TOKENS:-16}"
export SKETCHSMILES_BEAM_SIZE="${SKETCHSMILES_BEAM_SIZE:-16}"
export SKETCHSMILES_SLURM_JOB_NAME="${SKETCHSMILES_SLURM_JOB_NAME:-sketchsmiles-5a4-lg}"
export SKETCHSMILES_SLURM_TIME="${SKETCHSMILES_SLURM_TIME:-16:00:00}"
export SKETCHSMILES_SLURM_MEM="${SKETCHSMILES_SLURM_MEM:-48G}"

echo "SketchMolCompare -> SketchSMILES Phase 5A-4 large Transformer"
echo "  run_name=$SKETCHSMILES_RUN_NAME"
echo "  hidden_dim=$SKETCHSMILES_HIDDEN_DIM"
echo "  embedding_dim=$SKETCHSMILES_EMBEDDING_DIM"
echo "  transformer_layers=$SKETCHSMILES_TRANSFORMER_LAYERS"
echo "  condition_tokens=$SKETCHSMILES_CONDITION_TOKENS"

bash "$SCRIPT_DIR/submit_sketchsmiles_5a4_transformer.sh" "$@"
