#!/usr/bin/env bash
# Submit a stronger image-conditioned Phase 5D fingerprint-reranked run.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SEED="${SKETCHMOL_COMPARE_SEED:-${SKETCHSMILES_SEED:-7}}"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SKETCHSMILES_DIR="$REPO_ROOT/SketchSMILES"

if [[ ! -d "$SKETCHSMILES_DIR" ]]; then
  echo "ERROR: SketchSMILES folder not found at $SKETCHSMILES_DIR" >&2
  exit 2
fi

cd "$SKETCHSMILES_DIR"

export SKETCHSMILES_SEED="$SEED"
export SKETCHSMILES_RUN_NAME="${SKETCHSMILES_RUN_NAME:-sketchmol_compare_phase5d_strong_seed${SEED}}"
export SKETCHSMILES_PAIR_DIR="${SKETCHSMILES_PAIR_DIR:-outputs/pairs/phys_50k}"
export SKETCHSMILES_HIDDEN_DIM="${SKETCHSMILES_HIDDEN_DIM:-512}"
export SKETCHSMILES_EMBEDDING_DIM="${SKETCHSMILES_EMBEDDING_DIM:-128}"
export SKETCHSMILES_ENCODER_CHANNELS="${SKETCHSMILES_ENCODER_CHANNELS:-96}"
export SKETCHSMILES_IMAGE_TOKEN_GRID="${SKETCHSMILES_IMAGE_TOKEN_GRID:-6}"
export SKETCHSMILES_TRANSFORMER_LAYERS="${SKETCHSMILES_TRANSFORMER_LAYERS:-6}"
export SKETCHSMILES_FINGERPRINT_LOSS_WEIGHT="${SKETCHSMILES_FINGERPRINT_LOSS_WEIGHT:-1.0}"
export SKETCHSMILES_BEAM_SIZE="${SKETCHSMILES_BEAM_SIZE:-16}"
export SKETCHSMILES_SLURM_JOB_NAME="${SKETCHSMILES_SLURM_JOB_NAME:-sketchsmiles-5d-strong}"
export SKETCHSMILES_SLURM_TIME="${SKETCHSMILES_SLURM_TIME:-16:00:00}"
export SKETCHSMILES_SLURM_MEM="${SKETCHSMILES_SLURM_MEM:-48G}"

echo "SketchMolCompare -> SketchSMILES Phase 5D strong fingerprint"
echo "  run_name=$SKETCHSMILES_RUN_NAME"
echo "  hidden_dim=$SKETCHSMILES_HIDDEN_DIM"
echo "  encoder_channels=$SKETCHSMILES_ENCODER_CHANNELS"
echo "  image_token_grid=$SKETCHSMILES_IMAGE_TOKEN_GRID"
echo "  fingerprint_loss_weight=$SKETCHSMILES_FINGERPRINT_LOSS_WEIGHT"
echo "  beam_size=$SKETCHSMILES_BEAM_SIZE"

bash scripts/submit_phase5d_image_fingerprint_decoder.sh "$@"
