#!/usr/bin/env bash
# Submit the bold Unified 3M MolEdit run: source-residual diffusion plus source-anchor clamp.

set -euo pipefail

export DM_DATA_ROOT="${DM_DATA_ROOT:-/scratch/bdong/datasets/Diffusion-Molecule}"
export SMU3M_DATASET_MODE=moledit
export SMMED_SUBMIT_DATASET_BUILD="${SMMED_SUBMIT_DATASET_BUILD:-0}"
export SMU3M_OUTPUT_DIR="${SMU3M_OUTPUT_DIR:-SketchMol-Unified-3MDiffusion/outputs/unified_generation_moledit_sourceanchored_v2}"
export SMU3M_MOLEDIT_TRAIN_SPLIT="${SMU3M_MOLEDIT_TRAIN_SPLIT:-$DM_DATA_ROOT/processed/moledit-instruct/enhanced_v1/splits/train.csv}"
export SMU3M_MOLEDIT_EVAL_SPLIT="${SMU3M_MOLEDIT_EVAL_SPLIT:-$DM_DATA_ROOT/processed/moledit-instruct/enhanced_v1/splits/eval_balanced.csv}"
export SMU3M_MIN_EDIT_SOURCE_TANIMOTO="${SMU3M_MIN_EDIT_SOURCE_TANIMOTO:-0.0}"
export SMU3M_REQUIRE_EDIT_QUALITY_COLUMNS="${SMU3M_REQUIRE_EDIT_QUALITY_COLUMNS:-0}"
export SMU3M_REQUIRE_EVAL_ORACLE_STRICT="${SMU3M_REQUIRE_EVAL_ORACLE_STRICT:-0}"

export SMU3M_DIFFUSION_TARGET="${SMU3M_DIFFUSION_TARGET:-source_residual}"
export SMU3M_SOURCE_AWARE_SHARED_GRADIENT="${SMU3M_SOURCE_AWARE_SHARED_GRADIENT:-1}"
export SMU3M_HARD_NEGATIVE_LOSS_WEIGHT="${SMU3M_HARD_NEGATIVE_LOSS_WEIGHT:-0.20}"
export SMU3M_SOURCE_SIMILARITY_LOSS_WEIGHT="${SMU3M_SOURCE_SIMILARITY_LOSS_WEIGHT:-0.30}"
export SMU3M_SOURCE_FINGERPRINT_PRIOR_BLEND="${SMU3M_SOURCE_FINGERPRINT_PRIOR_BLEND:-0.90}"
export SMU3M_FINGERPRINT_GUARD_LOSS_WEIGHT="${SMU3M_FINGERPRINT_GUARD_LOSS_WEIGHT:-0.75}"
export SMU3M_SOURCE_RADIUS_LOSS_WEIGHT="${SMU3M_SOURCE_RADIUS_LOSS_WEIGHT:-0.25}"
export SMU3M_SOURCE_RESIDUAL_RADIUS_MULTIPLIER="${SMU3M_SOURCE_RESIDUAL_RADIUS_MULTIPLIER:-1.25}"
export SMU3M_SOURCE_RESIDUAL_RADIUS_MARGIN="${SMU3M_SOURCE_RESIDUAL_RADIUS_MARGIN:-0.05}"
export SMU3M_SOURCE_RESIDUAL_MIN_RADIUS="${SMU3M_SOURCE_RESIDUAL_MIN_RADIUS:-0.05}"
export SMU3M_SLURM_JOB_NAME="${SMU3M_SLURM_JOB_NAME:-smu3m-srcanch-v2}"

bash "$(dirname "${BASH_SOURCE[0]}")/submit_unified_generation_pipeline.sh"
