#!/bin/bash
#SBATCH --account=def-hup-ab
# 10GB H100 MIG（Nibi）；整卡用 #SBATCH --gpus=h100:1
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb:1
#SBATCH --mem=96G
#SBATCH --time=10:00:00
#SBATCH --cpus-per-task=16
#SBATCH --output=./slurm-%j.log
#SBATCH --error=./slurm-%j.log
#SBATCH --mail-user=dongbochen1218@gmail.com
#SBATCH --mail-type=BEGIN

set -euo pipefail
unset LD_LIBRARY_PATH
unset PYTHONPATH

# Slurm copies this script to /var/spool/slurmd/.../slurm_script — dirname(BASH_SOURCE) is not the repo.
# Submit from PhysTabMol repo root: cd .../PhysTabMol && sbatch scripts/run_phystabmol_gpu.slurm.sh
if [[ -n "${SLURM_JOB_ID:-}" && -n "${SLURM_SUBMIT_DIR:-}" ]]; then
  PHYSTABMOL_ROOT="$SLURM_SUBMIT_DIR"
else
  PHYSTABMOL_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
SCRIPT_DIR="$PHYSTABMOL_ROOT/scripts"
cd "$PHYSTABMOL_ROOT"

# Align system CUDA libs with PyTorch cu124 wheel; override with MODULE_CUDA=... if needed.
export MODULE_CUDA="${MODULE_CUDA:-cuda/12.6}"

# shellcheck source=/dev/null
source "$SCRIPT_DIR/env_module_venv.sh"

echo "jobid=${SLURM_JOB_ID:-} node=$(hostname) cwd=$(pwd)"
nvidia-smi || true
python -c "import torch; print('cuda=', torch.cuda.is_available())" || true

# Defaults match ChEMBL download -> data/molecules.csv (single "smiles" column).
# Override when submitting, e.g.:
#   PHYSTABMOL_DATA=/path/to.csv PHYSTABMOL_RUN_NAME=my_run sbatch scripts/run_phystabmol_gpu.slurm.sh
# Larger GPU/MIG runs can use larger torch knobs, e.g.:
#   PHYSTABMOL_TORCH_BATCH_SIZE=2048 PHYSTABMOL_TORCH_HIDDEN_DIM=1536 PHYSTABMOL_TORCH_LAYERS=8 sbatch scripts/run_phystabmol_gpu.slurm.sh
# Command-line sbatch options can also override the MIG slice requested above if your allocation allows it.
PHYSTABMOL_DATA="${PHYSTABMOL_DATA:-data/molecules.csv}"
PHYSTABMOL_BACKEND="${PHYSTABMOL_BACKEND:-torch}"
PHYSTABMOL_RUN_NAME="${PHYSTABMOL_RUN_NAME:-slurm_${SLURM_JOB_ID:-manual}}"
PHYSTABMOL_SAMPLES="${PHYSTABMOL_SAMPLES:-8}"
PHYSTABMOL_DECODE_TOP_K="${PHYSTABMOL_DECODE_TOP_K:-2}"
PHYSTABMOL_LIMIT="${PHYSTABMOL_LIMIT:-100000}"
PHYSTABMOL_TEST_FRACTION="${PHYSTABMOL_TEST_FRACTION:-0.05}"
PHYSTABMOL_CONTRASTIVE_EPOCHS="${PHYSTABMOL_CONTRASTIVE_EPOCHS:-80}"
PHYSTABMOL_CONTRASTIVE_BATCH_SIZE="${PHYSTABMOL_CONTRASTIVE_BATCH_SIZE:-512}"
PHYSTABMOL_CONTRASTIVE_MAX_PAIRS="${PHYSTABMOL_CONTRASTIVE_MAX_PAIRS:-20000}"
PHYSTABMOL_CONTRASTIVE_RETRIEVAL="${PHYSTABMOL_CONTRASTIVE_RETRIEVAL:-2048}"
PHYSTABMOL_TORCH_EPOCHS="${PHYSTABMOL_TORCH_EPOCHS:-80}"
PHYSTABMOL_TORCH_BATCH_SIZE="${PHYSTABMOL_TORCH_BATCH_SIZE:-1024}"
PHYSTABMOL_TORCH_HIDDEN_DIM="${PHYSTABMOL_TORCH_HIDDEN_DIM:-1024}"
PHYSTABMOL_TORCH_LAYERS="${PHYSTABMOL_TORCH_LAYERS:-6}"
PHYSTABMOL_TORCH_LR="${PHYSTABMOL_TORCH_LR:-0.0002}"
PHYSTABMOL_SAMPLE_CHUNK_SIZE="${PHYSTABMOL_SAMPLE_CHUNK_SIZE:-8192}"
PHYSTABMOL_TIMESTEPS="${PHYSTABMOL_TIMESTEPS:-80}"
PHYSTABMOL_NOISE_REPEATS="${PHYSTABMOL_NOISE_REPEATS:-8}"
PHYSTABMOL_TARGET_ANCHOR="${PHYSTABMOL_TARGET_ANCHOR:-1.0}"
PHYSTABMOL_ANCHOR_NEIGHBORS="${PHYSTABMOL_ANCHOR_NEIGHBORS:-128}"
PHYSTABMOL_COUNT_ANCHOR_WEIGHT="${PHYSTABMOL_COUNT_ANCHOR_WEIGHT:-0.8}"
PHYSTABMOL_DYNAMIC_DECODER="${PHYSTABMOL_DYNAMIC_DECODER:-0}"
PHYSTABMOL_PROPERTY_MASK_CONDITIONING="${PHYSTABMOL_PROPERTY_MASK_CONDITIONING:-0}"
PHYSTABMOL_RUN_SKETCHMOL_BENCHMARK="${PHYSTABMOL_RUN_SKETCHMOL_BENCHMARK:-0}"
PHYSTABMOL_BENCHMARK_SINGLE_CONDITIONS="${PHYSTABMOL_BENCHMARK_SINGLE_CONDITIONS:-125}"
PHYSTABMOL_BENCHMARK_SAMPLES="${PHYSTABMOL_BENCHMARK_SAMPLES:-100}"
PHYSTABMOL_BENCHMARK_DECODE_TOP_K="${PHYSTABMOL_BENCHMARK_DECODE_TOP_K:-1}"
PHYSTABMOL_BENCHMARK_MULTI_CONDITIONS="${PHYSTABMOL_BENCHMARK_MULTI_CONDITIONS:-200}"
PHYSTABMOL_BENCHMARK_OPTIMIZATION_CONDITIONS="${PHYSTABMOL_BENCHMARK_OPTIMIZATION_CONDITIONS:-100}"
PHYSTABMOL_RUN_STRUCTURE_PROMPT_BENCHMARK="${PHYSTABMOL_RUN_STRUCTURE_PROMPT_BENCHMARK:-0}"
PHYSTABMOL_STRUCTURE_PROMPT_CONDITIONS="${PHYSTABMOL_STRUCTURE_PROMPT_CONDITIONS:-200}"
PHYSTABMOL_STRUCTURE_PROMPT_SAMPLES="${PHYSTABMOL_STRUCTURE_PROMPT_SAMPLES:-8}"
PHYSTABMOL_STRUCTURE_PROMPT_DECODE_TOP_K="${PHYSTABMOL_STRUCTURE_PROMPT_DECODE_TOP_K:-2}"

EXTRA_ARGS=()
if [[ "$PHYSTABMOL_DYNAMIC_DECODER" == "1" ]]; then
  EXTRA_ARGS+=(--dynamic-decoder)
fi
if [[ "$PHYSTABMOL_PROPERTY_MASK_CONDITIONING" == "1" ]]; then
  EXTRA_ARGS+=(--property-mask-conditioning)
fi
if [[ "$PHYSTABMOL_RUN_SKETCHMOL_BENCHMARK" == "1" ]]; then
  EXTRA_ARGS+=(
    --run-sketchmol-benchmark
    --benchmark-single-conditions "$PHYSTABMOL_BENCHMARK_SINGLE_CONDITIONS"
    --benchmark-samples-per-condition "$PHYSTABMOL_BENCHMARK_SAMPLES"
    --benchmark-decode-top-k "$PHYSTABMOL_BENCHMARK_DECODE_TOP_K"
    --benchmark-multi-conditions "$PHYSTABMOL_BENCHMARK_MULTI_CONDITIONS"
    --benchmark-optimization-conditions "$PHYSTABMOL_BENCHMARK_OPTIMIZATION_CONDITIONS"
  )
fi
if [[ "$PHYSTABMOL_RUN_STRUCTURE_PROMPT_BENCHMARK" == "1" ]]; then
  EXTRA_ARGS+=(
    --run-structure-prompt-benchmark
    --structure-prompt-conditions "$PHYSTABMOL_STRUCTURE_PROMPT_CONDITIONS"
    --structure-prompt-samples "$PHYSTABMOL_STRUCTURE_PROMPT_SAMPLES"
    --structure-prompt-decode-top-k "$PHYSTABMOL_STRUCTURE_PROMPT_DECODE_TOP_K"
  )
fi

if [[ ! -s "$PHYSTABMOL_DATA" ]]; then
  echo "Dataset not found at $PHYSTABMOL_DATA; downloading ChEMBL first."
  PHYSTABMOL_OUT="$PHYSTABMOL_DATA" bash scripts/download_chembl_100k.sh --rdkit-filter
fi

python -m phystabmol.experiment \
  --data "$PHYSTABMOL_DATA" \
  --limit "$PHYSTABMOL_LIMIT" \
  --test-fraction "$PHYSTABMOL_TEST_FRACTION" \
  --backend "$PHYSTABMOL_BACKEND" \
  --run-name "$PHYSTABMOL_RUN_NAME" \
  --contrastive-epochs "$PHYSTABMOL_CONTRASTIVE_EPOCHS" \
  --contrastive-batch-size "$PHYSTABMOL_CONTRASTIVE_BATCH_SIZE" \
  --contrastive-max-pairs "$PHYSTABMOL_CONTRASTIVE_MAX_PAIRS" \
  --contrastive-retrieval-samples "$PHYSTABMOL_CONTRASTIVE_RETRIEVAL" \
  --torch-epochs "$PHYSTABMOL_TORCH_EPOCHS" \
  --torch-batch-size "$PHYSTABMOL_TORCH_BATCH_SIZE" \
  --torch-hidden-dim "$PHYSTABMOL_TORCH_HIDDEN_DIM" \
  --torch-layers "$PHYSTABMOL_TORCH_LAYERS" \
  --torch-lr "$PHYSTABMOL_TORCH_LR" \
  --sample-chunk-size "$PHYSTABMOL_SAMPLE_CHUNK_SIZE" \
  --timesteps "$PHYSTABMOL_TIMESTEPS" \
  --noise-repeats "$PHYSTABMOL_NOISE_REPEATS" \
  --target-anchor "$PHYSTABMOL_TARGET_ANCHOR" \
  --anchor-neighbors "$PHYSTABMOL_ANCHOR_NEIGHBORS" \
  --count-anchor-weight "$PHYSTABMOL_COUNT_ANCHOR_WEIGHT" \
  --samples-per-condition "$PHYSTABMOL_SAMPLES" \
  --decode-top-k "$PHYSTABMOL_DECODE_TOP_K" \
  "${EXTRA_ARGS[@]}"

echo "PhysTabMol job finished at $(date -Is)"
