#!/usr/bin/env bash
# Run Phase 2B: planner-aware fine-tuning for the Phase 1 latent decoder.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

PYTHON_BIN="${SKETCHIMAGE_PYTHON_BIN:-${PYTHON_BIN:-python3}}"
RUN_NAME="${SKETCHIMAGE_RUN_NAME:-phase2_robust_decoder_2048_seed${SKETCHIMAGE_SEED:-7}}"
OUTPUT_DIR="${SKETCHIMAGE_OUTPUT_DIR:-outputs/runs/$RUN_NAME}"

export SKETCHIMAGE_SEED="${SKETCHIMAGE_SEED:-7}"
export SKETCHIMAGE_ORACLE_DECODER_DIR="${SKETCHIMAGE_ORACLE_DECODER_DIR:-outputs/runs/phase1_oracle_latent_ar_2048_seed${SKETCHIMAGE_SEED}}"
export SKETCHIMAGE_TRAIN_CSV="${SKETCHIMAGE_TRAIN_CSV:-outputs/tasks/sketchmol_hard_seed${SKETCHIMAGE_SEED}_train.csv}"
export SKETCHIMAGE_EVAL_CSV="${SKETCHIMAGE_EVAL_CSV:-outputs/tasks/sketchmol_hard_seed${SKETCHIMAGE_SEED}_eval.csv}"
export SKETCHIMAGE_FEATURE_DIM="${SKETCHIMAGE_FEATURE_DIM:-256}"
export SKETCHIMAGE_TOP_K="${SKETCHIMAGE_TOP_K:-8}"
export SKETCHIMAGE_RIDGE="${SKETCHIMAGE_RIDGE:-0.001}"
export SKETCHIMAGE_BACKEND="${SKETCHIMAGE_BACKEND:-torch_denoiser}"
export SKETCHIMAGE_TORCH_HIDDEN_DIM="${SKETCHIMAGE_TORCH_HIDDEN_DIM:-1024}"
export SKETCHIMAGE_TORCH_EPOCHS="${SKETCHIMAGE_TORCH_EPOCHS:-25}"
export SKETCHIMAGE_TORCH_BATCH_SIZE="${SKETCHIMAGE_TORCH_BATCH_SIZE:-128}"
export SKETCHIMAGE_TORCH_LR="${SKETCHIMAGE_TORCH_LR:-0.001}"
export SKETCHIMAGE_TORCH_WEIGHT_DECAY="${SKETCHIMAGE_TORCH_WEIGHT_DECAY:-0.0001}"
export SKETCHIMAGE_TORCH_DIFFUSION_STEPS="${SKETCHIMAGE_TORCH_DIFFUSION_STEPS:-16}"
export SKETCHIMAGE_TORCH_TRAIN_NOISE="${SKETCHIMAGE_TORCH_TRAIN_NOISE:-0.35}"
export SKETCHIMAGE_TORCH_DIRECT_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_DIRECT_LOSS_WEIGHT:-1.0}"
export SKETCHIMAGE_TORCH_DELTA_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_DELTA_LOSS_WEIGHT:-0.2}"
export SKETCHIMAGE_TORCH_COSINE_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_COSINE_LOSS_WEIGHT:-2.0}"
export SKETCHIMAGE_TORCH_POSITIVE_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_POSITIVE_LOSS_WEIGHT:-12.0}"
export SKETCHIMAGE_TORCH_CONTRASTIVE_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_CONTRASTIVE_LOSS_WEIGHT:-0.75}"
export SKETCHIMAGE_TORCH_CONTRASTIVE_TEMPERATURE="${SKETCHIMAGE_TORCH_CONTRASTIVE_TEMPERATURE:-0.04}"
export SKETCHIMAGE_TORCH_HARD_NEGATIVE_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_HARD_NEGATIVE_LOSS_WEIGHT:-0.0}"
export SKETCHIMAGE_TORCH_HARD_NEGATIVE_MARGIN="${SKETCHIMAGE_TORCH_HARD_NEGATIVE_MARGIN:-0.10}"
export SKETCHIMAGE_TORCH_DEVICE="${SKETCHIMAGE_TORCH_DEVICE:-auto}"
export SKETCHIMAGE_DECODER_DEVICE="${SKETCHIMAGE_DECODER_DEVICE:-auto}"
export SKETCHIMAGE_RENDER_IMAGE_CONTEXT="${SKETCHIMAGE_RENDER_IMAGE_CONTEXT:-1}"
export SKETCHIMAGE_DECODER_FINETUNE_EPOCHS="${SKETCHIMAGE_DECODER_FINETUNE_EPOCHS:-8}"
export SKETCHIMAGE_DECODER_FINETUNE_BATCH_SIZE="${SKETCHIMAGE_DECODER_FINETUNE_BATCH_SIZE:-128}"
export SKETCHIMAGE_DECODER_FINETUNE_LR="${SKETCHIMAGE_DECODER_FINETUNE_LR:-0.0001}"
export SKETCHIMAGE_DECODER_FINETUNE_WEIGHT_DECAY="${SKETCHIMAGE_DECODER_FINETUNE_WEIGHT_DECAY:-0.0001}"
export SKETCHIMAGE_DECODER_ORACLE_REPEATS="${SKETCHIMAGE_DECODER_ORACLE_REPEATS:-1}"
export SKETCHIMAGE_DECODER_PLANNER_REPEATS="${SKETCHIMAGE_DECODER_PLANNER_REPEATS:-2}"
export SKETCHIMAGE_DECODER_NOISE_REPEATS="${SKETCHIMAGE_DECODER_NOISE_REPEATS:-1}"
export SKETCHIMAGE_DECODER_NOISE_STD="${SKETCHIMAGE_DECODER_NOISE_STD:-0.05}"
export SKETCHIMAGE_DECODER_INTERPOLATION_REPEATS="${SKETCHIMAGE_DECODER_INTERPOLATION_REPEATS:-1}"
export SKETCHIMAGE_DECODER_INTERPOLATION_ALPHA="${SKETCHIMAGE_DECODER_INTERPOLATION_ALPHA:-0.5}"

echo "SketchImage-JEPA Phase 2B robust planned decoder"
echo "  python=$PYTHON_BIN"
echo "  run_root=$OUTPUT_DIR"
echo "  oracle_decoder_dir=$SKETCHIMAGE_ORACLE_DECODER_DIR"
echo "  train_csv=$SKETCHIMAGE_TRAIN_CSV"
echo "  eval_csv=$SKETCHIMAGE_EVAL_CSV"
echo "  feature_dim=$SKETCHIMAGE_FEATURE_DIM"
echo "  latent_dim=${SKETCHIMAGE_LATENT_DIM:-<decoder condition dim>}"
echo "  top_k=$SKETCHIMAGE_TOP_K"
echo "  backend=$SKETCHIMAGE_BACKEND"
echo "  torch_device=$SKETCHIMAGE_TORCH_DEVICE"
echo "  decoder_device=$SKETCHIMAGE_DECODER_DEVICE"
echo "  torch_epochs=$SKETCHIMAGE_TORCH_EPOCHS"
echo "  torch_hidden_dim=$SKETCHIMAGE_TORCH_HIDDEN_DIM"
echo "  torch_batch_size=$SKETCHIMAGE_TORCH_BATCH_SIZE"
echo "  torch_contrastive_loss_weight=$SKETCHIMAGE_TORCH_CONTRASTIVE_LOSS_WEIGHT"
echo "  torch_contrastive_temperature=$SKETCHIMAGE_TORCH_CONTRASTIVE_TEMPERATURE"
echo "  decoder_finetune_epochs=$SKETCHIMAGE_DECODER_FINETUNE_EPOCHS"
echo "  decoder_finetune_lr=$SKETCHIMAGE_DECODER_FINETUNE_LR"
echo "  decoder_oracle_repeats=$SKETCHIMAGE_DECODER_ORACLE_REPEATS"
echo "  decoder_planner_repeats=$SKETCHIMAGE_DECODER_PLANNER_REPEATS"
echo "  decoder_noise_repeats=$SKETCHIMAGE_DECODER_NOISE_REPEATS"
echo "  decoder_noise_std=$SKETCHIMAGE_DECODER_NOISE_STD"
echo "  decoder_interpolation_repeats=$SKETCHIMAGE_DECODER_INTERPOLATION_REPEATS"
echo "  decoder_interpolation_alpha=$SKETCHIMAGE_DECODER_INTERPOLATION_ALPHA"
echo "  seed=$SKETCHIMAGE_SEED"
echo

if [[ ! -e "$SKETCHIMAGE_ORACLE_DECODER_DIR/model.pt" && ! -e "$SKETCHIMAGE_ORACLE_DECODER_DIR/model/model.pt" ]]; then
  echo "ERROR: Phase 1 decoder model not found under SKETCHIMAGE_ORACLE_DECODER_DIR=$SKETCHIMAGE_ORACLE_DECODER_DIR" >&2
  exit 2
fi
if [[ ! -f "$SKETCHIMAGE_TRAIN_CSV" ]]; then
  echo "ERROR: training CSV not found: $SKETCHIMAGE_TRAIN_CSV" >&2
  exit 2
fi
if [[ ! -f "$SKETCHIMAGE_EVAL_CSV" ]]; then
  echo "ERROR: eval CSV not found: $SKETCHIMAGE_EVAL_CSV" >&2
  exit 2
fi

if [[ "${SKETCHIMAGE_RUN_TESTS:-1}" == "1" ]]; then
  echo "[1/2] Running tests"
  "$PYTHON_BIN" -m unittest discover -s tests
  echo
else
  echo "[1/2] Skipping tests because SKETCHIMAGE_RUN_TESTS=$SKETCHIMAGE_RUN_TESTS"
  echo
fi

echo "[2/2] Training planner, fine-tuning decoder, and decoding eval predicted latents"
LATENT_ARGS=()
if [[ -n "${SKETCHIMAGE_LATENT_DIM:-}" ]]; then
  LATENT_ARGS+=(--latent-dim "$SKETCHIMAGE_LATENT_DIM")
fi
RENDER_ARGS=()
if [[ "$SKETCHIMAGE_RENDER_IMAGE_CONTEXT" == "1" ]]; then
  RENDER_ARGS+=(--render-image-context)
fi

"$PYTHON_BIN" -m sketchimage_jepa.phase2_robust_decoder \
  --oracle-decoder-dir "$SKETCHIMAGE_ORACLE_DECODER_DIR" \
  --output-dir "$OUTPUT_DIR" \
  --train-csv "$SKETCHIMAGE_TRAIN_CSV" \
  --eval-csv "$SKETCHIMAGE_EVAL_CSV" \
  --feature-dim "$SKETCHIMAGE_FEATURE_DIM" \
  "${LATENT_ARGS[@]}" \
  --top-k "$SKETCHIMAGE_TOP_K" \
  --ridge "$SKETCHIMAGE_RIDGE" \
  --backend "$SKETCHIMAGE_BACKEND" \
  --torch-hidden-dim "$SKETCHIMAGE_TORCH_HIDDEN_DIM" \
  --torch-epochs "$SKETCHIMAGE_TORCH_EPOCHS" \
  --torch-batch-size "$SKETCHIMAGE_TORCH_BATCH_SIZE" \
  --torch-lr "$SKETCHIMAGE_TORCH_LR" \
  --torch-weight-decay "$SKETCHIMAGE_TORCH_WEIGHT_DECAY" \
  --torch-diffusion-steps "$SKETCHIMAGE_TORCH_DIFFUSION_STEPS" \
  --torch-train-noise "$SKETCHIMAGE_TORCH_TRAIN_NOISE" \
  --torch-direct-loss-weight "$SKETCHIMAGE_TORCH_DIRECT_LOSS_WEIGHT" \
  --torch-delta-loss-weight "$SKETCHIMAGE_TORCH_DELTA_LOSS_WEIGHT" \
  --torch-cosine-loss-weight "$SKETCHIMAGE_TORCH_COSINE_LOSS_WEIGHT" \
  --torch-positive-loss-weight "$SKETCHIMAGE_TORCH_POSITIVE_LOSS_WEIGHT" \
  --torch-contrastive-loss-weight "$SKETCHIMAGE_TORCH_CONTRASTIVE_LOSS_WEIGHT" \
  --torch-contrastive-temperature "$SKETCHIMAGE_TORCH_CONTRASTIVE_TEMPERATURE" \
  --torch-hard-negative-loss-weight "$SKETCHIMAGE_TORCH_HARD_NEGATIVE_LOSS_WEIGHT" \
  --torch-hard-negative-margin "$SKETCHIMAGE_TORCH_HARD_NEGATIVE_MARGIN" \
  --torch-device "$SKETCHIMAGE_TORCH_DEVICE" \
  --decoder-device "$SKETCHIMAGE_DECODER_DEVICE" \
  --decoder-finetune-epochs "$SKETCHIMAGE_DECODER_FINETUNE_EPOCHS" \
  --decoder-finetune-batch-size "$SKETCHIMAGE_DECODER_FINETUNE_BATCH_SIZE" \
  --decoder-finetune-lr "$SKETCHIMAGE_DECODER_FINETUNE_LR" \
  --decoder-finetune-weight-decay "$SKETCHIMAGE_DECODER_FINETUNE_WEIGHT_DECAY" \
  --decoder-oracle-repeats "$SKETCHIMAGE_DECODER_ORACLE_REPEATS" \
  --decoder-planner-repeats "$SKETCHIMAGE_DECODER_PLANNER_REPEATS" \
  --decoder-noise-repeats "$SKETCHIMAGE_DECODER_NOISE_REPEATS" \
  --decoder-noise-std "$SKETCHIMAGE_DECODER_NOISE_STD" \
  --decoder-interpolation-repeats "$SKETCHIMAGE_DECODER_INTERPOLATION_REPEATS" \
  --decoder-interpolation-alpha "$SKETCHIMAGE_DECODER_INTERPOLATION_ALPHA" \
  --seed "$SKETCHIMAGE_SEED" \
  "${RENDER_ARGS[@]}"

echo
echo "Phase 2B robust planned decoder finished: $OUTPUT_DIR"
echo "  metrics=$OUTPUT_DIR/metrics.json"
echo "  predictions=$OUTPUT_DIR/predictions.csv"
echo "  config=$OUTPUT_DIR/run_config.json"
