#!/usr/bin/env bash
# Run Phase 4A: source-conditioned edit/action latent planner.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

PYTHON_BIN="${SKETCHIMAGE_PYTHON_BIN:-${PYTHON_BIN:-python3}}"
RUN_NAME="${SKETCHIMAGE_RUN_NAME:-phase4_edit_action_planner_2048_seed${SKETCHIMAGE_SEED:-7}}"
OUTPUT_DIR="${SKETCHIMAGE_OUTPUT_DIR:-outputs/runs/$RUN_NAME}"

export SKETCHIMAGE_SEED="${SKETCHIMAGE_SEED:-7}"
export SKETCHIMAGE_ORACLE_DECODER_DIR="${SKETCHIMAGE_ORACLE_DECODER_DIR:-outputs/runs/phase1_oracle_latent_ar_2048_seed${SKETCHIMAGE_SEED}}"
export SKETCHIMAGE_TRAIN_CSV="${SKETCHIMAGE_TRAIN_CSV:-outputs/tasks/sketchmol_hard_seed${SKETCHIMAGE_SEED}_train.csv}"
export SKETCHIMAGE_EVAL_CSV="${SKETCHIMAGE_EVAL_CSV:-outputs/tasks/sketchmol_hard_seed${SKETCHIMAGE_SEED}_eval.csv}"
export SKETCHIMAGE_FEATURE_DIM="${SKETCHIMAGE_FEATURE_DIM:-256}"
export SKETCHIMAGE_TOP_K="${SKETCHIMAGE_TOP_K:-8}"
export SKETCHIMAGE_SAMPLES_PER_ALPHA="${SKETCHIMAGE_SAMPLES_PER_ALPHA:-2}"
export SKETCHIMAGE_ACTION_ALPHAS="${SKETCHIMAGE_ACTION_ALPHAS:-0.25,0.50,0.75,1.00,1.25}"
export SKETCHIMAGE_ALPHA_SCORE_PENALTY="${SKETCHIMAGE_ALPHA_SCORE_PENALTY:-0.02}"
export SKETCHIMAGE_ACTION_TARGET_MODE="${SKETCHIMAGE_ACTION_TARGET_MODE:-raw_delta}"
export SKETCHIMAGE_ACTION_STEP_MODE="${SKETCHIMAGE_ACTION_STEP_MODE:-implicit}"
export SKETCHIMAGE_ACTION_STEP_RIDGE="${SKETCHIMAGE_ACTION_STEP_RIDGE:-0.01}"
export SKETCHIMAGE_ACTION_STEP_CLIP_QUANTILE="${SKETCHIMAGE_ACTION_STEP_CLIP_QUANTILE:-0.98}"
export SKETCHIMAGE_ACTION_CORRECTION_MODE="${SKETCHIMAGE_ACTION_CORRECTION_MODE:-none}"
export SKETCHIMAGE_ACTION_NEIGHBOR_KEY="${SKETCHIMAGE_ACTION_NEIGHBOR_KEY:-condition_source}"
export SKETCHIMAGE_ACTION_NEIGHBOR_COUNT="${SKETCHIMAGE_ACTION_NEIGHBOR_COUNT:-16}"
export SKETCHIMAGE_ACTION_NEIGHBOR_TEMPERATURE="${SKETCHIMAGE_ACTION_NEIGHBOR_TEMPERATURE:-0.07}"
export SKETCHIMAGE_ACTION_NEIGHBOR_BLEND="${SKETCHIMAGE_ACTION_NEIGHBOR_BLEND:-0.5}"
export SKETCHIMAGE_RIDGE="${SKETCHIMAGE_RIDGE:-0.001}"
export SKETCHIMAGE_BACKEND="${SKETCHIMAGE_BACKEND:-torch_denoiser}"
export SKETCHIMAGE_TORCH_HIDDEN_DIM="${SKETCHIMAGE_TORCH_HIDDEN_DIM:-1024}"
export SKETCHIMAGE_TORCH_EPOCHS="${SKETCHIMAGE_TORCH_EPOCHS:-35}"
export SKETCHIMAGE_TORCH_BATCH_SIZE="${SKETCHIMAGE_TORCH_BATCH_SIZE:-128}"
export SKETCHIMAGE_TORCH_LR="${SKETCHIMAGE_TORCH_LR:-0.001}"
export SKETCHIMAGE_TORCH_WEIGHT_DECAY="${SKETCHIMAGE_TORCH_WEIGHT_DECAY:-0.0001}"
export SKETCHIMAGE_TORCH_DIFFUSION_STEPS="${SKETCHIMAGE_TORCH_DIFFUSION_STEPS:-16}"
export SKETCHIMAGE_TORCH_TRAIN_NOISE="${SKETCHIMAGE_TORCH_TRAIN_NOISE:-0.35}"
export SKETCHIMAGE_TORCH_DIRECT_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_DIRECT_LOSS_WEIGHT:-1.0}"
export SKETCHIMAGE_TORCH_DELTA_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_DELTA_LOSS_WEIGHT:-0.0}"
export SKETCHIMAGE_TORCH_COSINE_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_COSINE_LOSS_WEIGHT:-2.0}"
export SKETCHIMAGE_TORCH_POSITIVE_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_POSITIVE_LOSS_WEIGHT:-12.0}"
export SKETCHIMAGE_TORCH_CONTRASTIVE_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_CONTRASTIVE_LOSS_WEIGHT:-0.75}"
export SKETCHIMAGE_TORCH_CONTRASTIVE_TEMPERATURE="${SKETCHIMAGE_TORCH_CONTRASTIVE_TEMPERATURE:-0.04}"
export SKETCHIMAGE_TORCH_HARD_NEGATIVE_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_HARD_NEGATIVE_LOSS_WEIGHT:-0.0}"
export SKETCHIMAGE_TORCH_HARD_NEGATIVE_MARGIN="${SKETCHIMAGE_TORCH_HARD_NEGATIVE_MARGIN:-0.10}"
export SKETCHIMAGE_TORCH_DEVICE="${SKETCHIMAGE_TORCH_DEVICE:-auto}"
export SKETCHIMAGE_DECODER_DEVICE="${SKETCHIMAGE_DECODER_DEVICE:-auto}"
export SKETCHIMAGE_ORACLE_ACTION_CONTROL="${SKETCHIMAGE_ORACLE_ACTION_CONTROL:-1}"
export SKETCHIMAGE_RENDER_IMAGE_CONTEXT="${SKETCHIMAGE_RENDER_IMAGE_CONTEXT:-1}"

echo "SketchImage-JEPA ${SKETCHIMAGE_PHASE_TITLE:-Phase 4A edit/action planner}"
echo "  python=$PYTHON_BIN"
echo "  run_root=$OUTPUT_DIR"
echo "  oracle_decoder_dir=$SKETCHIMAGE_ORACLE_DECODER_DIR"
echo "  train_csv=$SKETCHIMAGE_TRAIN_CSV"
echo "  eval_csv=$SKETCHIMAGE_EVAL_CSV"
echo "  feature_dim=$SKETCHIMAGE_FEATURE_DIM"
echo "  latent_dim=${SKETCHIMAGE_LATENT_DIM:-<decoder condition dim>}"
echo "  top_k=$SKETCHIMAGE_TOP_K"
echo "  samples_per_alpha=$SKETCHIMAGE_SAMPLES_PER_ALPHA"
echo "  action_alphas=$SKETCHIMAGE_ACTION_ALPHAS"
echo "  alpha_score_penalty=$SKETCHIMAGE_ALPHA_SCORE_PENALTY"
echo "  action_target_mode=$SKETCHIMAGE_ACTION_TARGET_MODE"
echo "  action_step_mode=$SKETCHIMAGE_ACTION_STEP_MODE"
echo "  action_step_ridge=$SKETCHIMAGE_ACTION_STEP_RIDGE"
echo "  action_step_clip_quantile=$SKETCHIMAGE_ACTION_STEP_CLIP_QUANTILE"
echo "  action_correction_mode=$SKETCHIMAGE_ACTION_CORRECTION_MODE"
echo "  action_neighbor_key=$SKETCHIMAGE_ACTION_NEIGHBOR_KEY"
echo "  action_neighbor_count=$SKETCHIMAGE_ACTION_NEIGHBOR_COUNT"
echo "  action_neighbor_temperature=$SKETCHIMAGE_ACTION_NEIGHBOR_TEMPERATURE"
echo "  action_neighbor_blend=$SKETCHIMAGE_ACTION_NEIGHBOR_BLEND"
echo "  backend=$SKETCHIMAGE_BACKEND"
echo "  torch_device=$SKETCHIMAGE_TORCH_DEVICE"
echo "  decoder_device=$SKETCHIMAGE_DECODER_DEVICE"
echo "  torch_epochs=$SKETCHIMAGE_TORCH_EPOCHS"
echo "  torch_hidden_dim=$SKETCHIMAGE_TORCH_HIDDEN_DIM"
echo "  torch_batch_size=$SKETCHIMAGE_TORCH_BATCH_SIZE"
echo "  torch_diffusion_steps=$SKETCHIMAGE_TORCH_DIFFUSION_STEPS"
echo "  torch_direct_loss_weight=$SKETCHIMAGE_TORCH_DIRECT_LOSS_WEIGHT"
echo "  torch_delta_loss_weight=$SKETCHIMAGE_TORCH_DELTA_LOSS_WEIGHT"
echo "  torch_cosine_loss_weight=$SKETCHIMAGE_TORCH_COSINE_LOSS_WEIGHT"
echo "  torch_positive_loss_weight=$SKETCHIMAGE_TORCH_POSITIVE_LOSS_WEIGHT"
echo "  torch_contrastive_loss_weight=$SKETCHIMAGE_TORCH_CONTRASTIVE_LOSS_WEIGHT"
echo "  torch_contrastive_temperature=$SKETCHIMAGE_TORCH_CONTRASTIVE_TEMPERATURE"
echo "  oracle_action_control=$SKETCHIMAGE_ORACLE_ACTION_CONTROL"
echo "  seed=$SKETCHIMAGE_SEED"
echo

if [[ ! -e "$SKETCHIMAGE_ORACLE_DECODER_DIR/model.pt" && ! -e "$SKETCHIMAGE_ORACLE_DECODER_DIR/model/model.pt" ]]; then
  echo "ERROR: Phase 1 decoder model not found under SKETCHIMAGE_ORACLE_DECODER_DIR=$SKETCHIMAGE_ORACLE_DECODER_DIR" >&2
  echo "Run Phase 1 first, or point SKETCHIMAGE_ORACLE_DECODER_DIR to a Phase 1 run directory." >&2
  exit 2
fi
if [[ ! -f "$SKETCHIMAGE_TRAIN_CSV" ]]; then
  echo "ERROR: training CSV not found: $SKETCHIMAGE_TRAIN_CSV" >&2
  exit 2
fi
if [[ ! -f "$SKETCHIMAGE_EVAL_CSV" ]]; then
  echo "ERROR: eval CSV not found: $SKETCHIMAGE_EVAL_CSV" >&2
  exit 2
fi

if [[ "${SKETCHIMAGE_RUN_TESTS:-1}" == "1" ]]; then
  echo "[1/2] Running tests"
  "$PYTHON_BIN" -m unittest discover -s tests
  echo
else
  echo "[1/2] Skipping tests because SKETCHIMAGE_RUN_TESTS=$SKETCHIMAGE_RUN_TESTS"
  echo
fi

echo "[2/2] Training edit/action planner and decoding alpha beam through frozen Phase 1 decoder"
LATENT_ARGS=()
if [[ -n "${SKETCHIMAGE_LATENT_DIM:-}" ]]; then
  LATENT_ARGS+=(--latent-dim "$SKETCHIMAGE_LATENT_DIM")
fi
RENDER_ARGS=()
if [[ "$SKETCHIMAGE_RENDER_IMAGE_CONTEXT" == "1" ]]; then
  RENDER_ARGS+=(--render-image-context)
fi
ORACLE_CONTROL_ARGS=(--no-oracle-action-control)
if [[ "$SKETCHIMAGE_ORACLE_ACTION_CONTROL" == "1" ]]; then
  ORACLE_CONTROL_ARGS=(--oracle-action-control)
fi

"$PYTHON_BIN" -m sketchimage_jepa.phase4_edit_action_planner \
  --oracle-decoder-dir "$SKETCHIMAGE_ORACLE_DECODER_DIR" \
  --output-dir "$OUTPUT_DIR" \
  --train-csv "$SKETCHIMAGE_TRAIN_CSV" \
  --eval-csv "$SKETCHIMAGE_EVAL_CSV" \
  --feature-dim "$SKETCHIMAGE_FEATURE_DIM" \
  "${LATENT_ARGS[@]}" \
  --top-k "$SKETCHIMAGE_TOP_K" \
  --samples-per-alpha "$SKETCHIMAGE_SAMPLES_PER_ALPHA" \
  --action-alphas "$SKETCHIMAGE_ACTION_ALPHAS" \
  --alpha-score-penalty "$SKETCHIMAGE_ALPHA_SCORE_PENALTY" \
  --action-target-mode "$SKETCHIMAGE_ACTION_TARGET_MODE" \
  --action-step-mode "$SKETCHIMAGE_ACTION_STEP_MODE" \
  --action-step-ridge "$SKETCHIMAGE_ACTION_STEP_RIDGE" \
  --action-step-clip-quantile "$SKETCHIMAGE_ACTION_STEP_CLIP_QUANTILE" \
  --action-correction-mode "$SKETCHIMAGE_ACTION_CORRECTION_MODE" \
  --action-neighbor-key "$SKETCHIMAGE_ACTION_NEIGHBOR_KEY" \
  --action-neighbor-count "$SKETCHIMAGE_ACTION_NEIGHBOR_COUNT" \
  --action-neighbor-temperature "$SKETCHIMAGE_ACTION_NEIGHBOR_TEMPERATURE" \
  --action-neighbor-blend "$SKETCHIMAGE_ACTION_NEIGHBOR_BLEND" \
  --ridge "$SKETCHIMAGE_RIDGE" \
  --backend "$SKETCHIMAGE_BACKEND" \
  --torch-hidden-dim "$SKETCHIMAGE_TORCH_HIDDEN_DIM" \
  --torch-epochs "$SKETCHIMAGE_TORCH_EPOCHS" \
  --torch-batch-size "$SKETCHIMAGE_TORCH_BATCH_SIZE" \
  --torch-lr "$SKETCHIMAGE_TORCH_LR" \
  --torch-weight-decay "$SKETCHIMAGE_TORCH_WEIGHT_DECAY" \
  --torch-diffusion-steps "$SKETCHIMAGE_TORCH_DIFFUSION_STEPS" \
  --torch-train-noise "$SKETCHIMAGE_TORCH_TRAIN_NOISE" \
  --torch-direct-loss-weight "$SKETCHIMAGE_TORCH_DIRECT_LOSS_WEIGHT" \
  --torch-delta-loss-weight "$SKETCHIMAGE_TORCH_DELTA_LOSS_WEIGHT" \
  --torch-cosine-loss-weight "$SKETCHIMAGE_TORCH_COSINE_LOSS_WEIGHT" \
  --torch-positive-loss-weight "$SKETCHIMAGE_TORCH_POSITIVE_LOSS_WEIGHT" \
  --torch-contrastive-loss-weight "$SKETCHIMAGE_TORCH_CONTRASTIVE_LOSS_WEIGHT" \
  --torch-contrastive-temperature "$SKETCHIMAGE_TORCH_CONTRASTIVE_TEMPERATURE" \
  --torch-hard-negative-loss-weight "$SKETCHIMAGE_TORCH_HARD_NEGATIVE_LOSS_WEIGHT" \
  --torch-hard-negative-margin "$SKETCHIMAGE_TORCH_HARD_NEGATIVE_MARGIN" \
  --torch-device "$SKETCHIMAGE_TORCH_DEVICE" \
  --decoder-device "$SKETCHIMAGE_DECODER_DEVICE" \
  --seed "$SKETCHIMAGE_SEED" \
  "${ORACLE_CONTROL_ARGS[@]}" \
  "${RENDER_ARGS[@]}"

echo
echo "${SKETCHIMAGE_PHASE_TITLE:-Phase 4A edit/action planner} finished: $OUTPUT_DIR"
echo "  metrics=$OUTPUT_DIR/metrics.json"
echo "  predictions=$OUTPUT_DIR/predictions.csv"
echo "  alpha_summary=$OUTPUT_DIR/alpha_summary.csv"
echo "  config=$OUTPUT_DIR/run_config.json"
