#!/usr/bin/env bash
# Run Phase 4C: retrieval-guided normalized edit/action planner.

set -euo pipefail

export SKETCHIMAGE_RUN_NAME="${SKETCHIMAGE_RUN_NAME:-phase4c_retrieval_action_planner_2048_seed${SKETCHIMAGE_SEED:-7}}"
export SKETCHIMAGE_PHASE_TITLE="${SKETCHIMAGE_PHASE_TITLE:-Phase 4C retrieval-guided edit/action planner}"
export SKETCHIMAGE_ACTION_TARGET_MODE="${SKETCHIMAGE_ACTION_TARGET_MODE:-unit_direction}"
export SKETCHIMAGE_ACTION_STEP_MODE="${SKETCHIMAGE_ACTION_STEP_MODE:-target_norm_median}"
export SKETCHIMAGE_ACTION_CORRECTION_MODE="${SKETCHIMAGE_ACTION_CORRECTION_MODE:-neighbor_direction}"
export SKETCHIMAGE_ACTION_NEIGHBOR_KEY="${SKETCHIMAGE_ACTION_NEIGHBOR_KEY:-condition_source}"
export SKETCHIMAGE_ACTION_NEIGHBOR_COUNT="${SKETCHIMAGE_ACTION_NEIGHBOR_COUNT:-24}"
export SKETCHIMAGE_ACTION_NEIGHBOR_TEMPERATURE="${SKETCHIMAGE_ACTION_NEIGHBOR_TEMPERATURE:-0.07}"
export SKETCHIMAGE_ACTION_NEIGHBOR_BLEND="${SKETCHIMAGE_ACTION_NEIGHBOR_BLEND:-0.50}"
export SKETCHIMAGE_ACTION_ALPHAS="${SKETCHIMAGE_ACTION_ALPHAS:-0.05,0.10,0.15,0.25,0.50,0.75,1.00}"
export SKETCHIMAGE_ALPHA_SCORE_PENALTY="${SKETCHIMAGE_ALPHA_SCORE_PENALTY:-0.01}"

bash "$(dirname "${BASH_SOURCE[0]}")/run_phase4_edit_action_planner.sh"
