#!/bin/bash
# Submit the first Stage-C prototype: a torch planner with a generative mutation
# decoder that can propose molecules outside the training target pool.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

export SKETCHIMAGE_BACKEND="${SKETCHIMAGE_BACKEND:-torch_denoiser}"
export SKETCHIMAGE_DECODER_MODE="${SKETCHIMAGE_DECODER_MODE:-hybrid_generative}"
export SKETCHIMAGE_RUN_NAME="${SKETCHIMAGE_RUN_NAME:-sketchmol_aligned_generative_decoder_$(date +%Y%m%d_%H%M%S)}"

# Start from the current best planner-side setting, then change the decoder.
export SKETCHIMAGE_DE_NOVO_LATENT_RERANK_WEIGHT="${SKETCHIMAGE_DE_NOVO_LATENT_RERANK_WEIGHT:-0.20}"
export SKETCHIMAGE_SOURCE_RERANK_WEIGHT="${SKETCHIMAGE_SOURCE_RERANK_WEIGHT:-0.25}"
export SKETCHIMAGE_PROPERTY_RERANK_WEIGHT="${SKETCHIMAGE_PROPERTY_RERANK_WEIGHT:-0.20}"
export SKETCHIMAGE_SCAFFOLD_RERANK_BONUS="${SKETCHIMAGE_SCAFFOLD_RERANK_BONUS:-0.10}"
export SKETCHIMAGE_TORCH_COSINE_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_COSINE_LOSS_WEIGHT:-2.0}"
export SKETCHIMAGE_TORCH_POSITIVE_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_POSITIVE_LOSS_WEIGHT:-12.0}"
export SKETCHIMAGE_TORCH_CONTRASTIVE_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_CONTRASTIVE_LOSS_WEIGHT:-0.75}"
export SKETCHIMAGE_TORCH_CONTRASTIVE_TEMPERATURE="${SKETCHIMAGE_TORCH_CONTRASTIVE_TEMPERATURE:-0.04}"

export SKETCHIMAGE_GENERATIVE_SEED_COUNT="${SKETCHIMAGE_GENERATIVE_SEED_COUNT:-24}"
export SKETCHIMAGE_GENERATIVE_MUTATION_ROUNDS="${SKETCHIMAGE_GENERATIVE_MUTATION_ROUNDS:-1}"
export SKETCHIMAGE_GENERATIVE_CANDIDATES_PER_SEED="${SKETCHIMAGE_GENERATIVE_CANDIDATES_PER_SEED:-8}"
export SKETCHIMAGE_GENERATIVE_NOVELTY_BONUS="${SKETCHIMAGE_GENERATIVE_NOVELTY_BONUS:-0.05}"

echo "Submitting Stage-C generative decoder prototype:"
echo "  run_name=$SKETCHIMAGE_RUN_NAME"
echo "  backend=$SKETCHIMAGE_BACKEND"
echo "  decoder_mode=$SKETCHIMAGE_DECODER_MODE"
echo "  generative_seed_count=$SKETCHIMAGE_GENERATIVE_SEED_COUNT"
echo "  generative_mutation_rounds=$SKETCHIMAGE_GENERATIVE_MUTATION_ROUNDS"
echo "  generative_candidates_per_seed=$SKETCHIMAGE_GENERATIVE_CANDIDATES_PER_SEED"
echo

bash scripts/submit_torch_denoiser.sh
