#!/bin/bash
# Submit the supervised edit-policy transform decoder. This variant learns a
# lightweight transform policy from source-target edit examples, then uses the
# predicted latent plan to choose edit actions at generation time.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

export SKETCHIMAGE_BACKEND="${SKETCHIMAGE_BACKEND:-torch_denoiser}"
export SKETCHIMAGE_DECODER_MODE="${SKETCHIMAGE_DECODER_MODE:-hybrid_edit_policy_transform}"
export SKETCHIMAGE_RUN_NAME="${SKETCHIMAGE_RUN_NAME:-sketchmol_aligned_edit_policy_transform_$(date +%Y%m%d_%H%M%S)}"

export SKETCHIMAGE_DE_NOVO_LATENT_RERANK_WEIGHT="${SKETCHIMAGE_DE_NOVO_LATENT_RERANK_WEIGHT:-0.20}"
export SKETCHIMAGE_SOURCE_RERANK_WEIGHT="${SKETCHIMAGE_SOURCE_RERANK_WEIGHT:-0.25}"
export SKETCHIMAGE_PROPERTY_RERANK_WEIGHT="${SKETCHIMAGE_PROPERTY_RERANK_WEIGHT:-0.20}"
export SKETCHIMAGE_SCAFFOLD_RERANK_BONUS="${SKETCHIMAGE_SCAFFOLD_RERANK_BONUS:-0.10}"
export SKETCHIMAGE_TORCH_COSINE_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_COSINE_LOSS_WEIGHT:-2.0}"
export SKETCHIMAGE_TORCH_POSITIVE_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_POSITIVE_LOSS_WEIGHT:-12.0}"
export SKETCHIMAGE_TORCH_CONTRASTIVE_LOSS_WEIGHT="${SKETCHIMAGE_TORCH_CONTRASTIVE_LOSS_WEIGHT:-0.75}"
export SKETCHIMAGE_TORCH_CONTRASTIVE_TEMPERATURE="${SKETCHIMAGE_TORCH_CONTRASTIVE_TEMPERATURE:-0.04}"

export SKETCHIMAGE_GENERATIVE_SEED_COUNT="${SKETCHIMAGE_GENERATIVE_SEED_COUNT:-64}"
export SKETCHIMAGE_GENERATIVE_MUTATION_ROUNDS="${SKETCHIMAGE_GENERATIVE_MUTATION_ROUNDS:-2}"
export SKETCHIMAGE_GENERATIVE_CANDIDATES_PER_SEED="${SKETCHIMAGE_GENERATIVE_CANDIDATES_PER_SEED:-16}"
export SKETCHIMAGE_GENERATIVE_NOVELTY_BONUS="${SKETCHIMAGE_GENERATIVE_NOVELTY_BONUS:-0.05}"

echo "Submitting supervised edit-policy transform decoder:"
echo "  run_name=$SKETCHIMAGE_RUN_NAME"
echo "  backend=$SKETCHIMAGE_BACKEND"
echo "  decoder_mode=$SKETCHIMAGE_DECODER_MODE"
echo "  transform_policy_limit=$SKETCHIMAGE_GENERATIVE_SEED_COUNT"
echo "  beam_width=$SKETCHIMAGE_GENERATIVE_CANDIDATES_PER_SEED"
echo "  beam_rounds=$SKETCHIMAGE_GENERATIVE_MUTATION_ROUNDS"
echo

bash scripts/submit_torch_denoiser.sh
