#!/usr/bin/env bash
# Run a tiny no-OCR end-to-end smoke experiment.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$PROJECT_DIR/.." && pwd)"
cd "$REPO_ROOT"

export SKETCHMOL_E2E_PYTHON_BIN="${SKETCHMOL_E2E_PYTHON_BIN:-${PYTHON_BIN:-python3}}"
export SKETCHMOL_E2E_PAIR_DIR="${SKETCHMOL_E2E_PAIR_DIR:-SketchSMILES/outputs/pairs/phys_50k}"
export SKETCHMOL_E2E_RUN_NAME="${SKETCHMOL_E2E_RUN_NAME:-smoke_image_to_structure}"
export SKETCHMOL_E2E_LIMIT="${SKETCHMOL_E2E_LIMIT:-64}"
export SKETCHMOL_E2E_EPOCHS="${SKETCHMOL_E2E_EPOCHS:-1}"
export SKETCHMOL_E2E_BATCH_SIZE="${SKETCHMOL_E2E_BATCH_SIZE:-16}"
export SKETCHMOL_E2E_HIDDEN_DIM="${SKETCHMOL_E2E_HIDDEN_DIM:-64}"
export SKETCHMOL_E2E_EMBEDDING_DIM="${SKETCHMOL_E2E_EMBEDDING_DIM:-32}"
export SKETCHMOL_E2E_ENCODER_CHANNELS="${SKETCHMOL_E2E_ENCODER_CHANNELS:-16}"
export SKETCHMOL_E2E_TRANSFORMER_LAYERS="${SKETCHMOL_E2E_TRANSFORMER_LAYERS:-1}"
export SKETCHMOL_E2E_ATTENTION_HEADS="${SKETCHMOL_E2E_ATTENTION_HEADS:-4}"
export SKETCHMOL_E2E_IMAGE_SIZE="${SKETCHMOL_E2E_IMAGE_SIZE:-64}"
export SKETCHMOL_E2E_SAMPLE_COUNT="${SKETCHMOL_E2E_SAMPLE_COUNT:-8}"
export SKETCHMOL_E2E_DEVICE="${SKETCHMOL_E2E_DEVICE:-cpu}"

echo "SketchMolEnd2End smoke"
echo "  pair_dir=$SKETCHMOL_E2E_PAIR_DIR"
echo "  run_name=$SKETCHMOL_E2E_RUN_NAME"

bash SketchMolEnd2End/scripts/run_image_to_structure.sh
